baseURL: "https://ikeike-da.github.io/"
title: Koki Ikeda
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 2
        - name: CV
          url: cv/
          weight: 3
        - name: Contact
          url: contact/
          weight: 4

params:
    description: "Ph.D. student in computer science working on black-box optimization and evolutionary computation."
    author: Koki Ikeda
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","cv","contact"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Koki Ikeda
          subtitle: "I am a Ph.D. student in computer science at Institute of Science Tokyo, Japan. My research focuses on mixed-variable black-box optimization and evolutionary computation, especially methods based on covariance matrix adaptation evolution strategies."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: CV
              url: cv/
            - name: Contact
              url: contact/
            - name: Tags
              url: tags/

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:ikeda.k@ic.comp.isct.ac.jp
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=CUco1x8AAAAJ
        - name: ORCID
          url: https://orcid.org/0009-0004-9588-3770
        - name: GitHub
          url: https://github.com/ikeike-da

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Koki Ikeda"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
